threads:
  min_delay: 1
  max_delay: 4
  max_scroll: 10
  max_concurrency: 1
  stop_on_login: true

ptt:
  min_delay: 0.5
  max_delay: 2
  max_scroll: 0
  max_concurrency: 2

google_maps:
  min_delay: 1
  max_delay: 3
  max_scroll: 5
  max_concurrency: 1
