from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SQL = (ROOT / "database" / "schema.sql").read_text(encoding="utf-8")
RELATIONSHIP_MIGRATION = (
    ROOT / "database" / "migrations" / "20260713_refactor_crawl_relationships_latest_only.sql"
).read_text(encoding="utf-8")


def _table_sql(name: str) -> str:
    return SQL.split(f"CREATE TABLE {name}", 1)[1].split(");", 1)[0]


def test_clean_schema_uses_bigint_identity_keys():
    for table in (
        "clients",
        "business",
        "service_tasks",
        "crawl_jobs",
        "crawl_logs",
        "crawl_posts",
        "crawl_comments",
        "post_metric_snapshots",
        "comment_metric_snapshots",
        "analysis_results",
        "reputation_score_snapshots",
        "alerts",
        "client_messages_log",
    ):
        assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in _table_sql(table)

    assert " UUID " not in SQL.upper()
    assert "human_id" not in SQL


def test_service_tasks_follow_dev_spec_config_boundary():
    service_task_sql = _table_sql("service_tasks")

    assert "business_id BIGINT" in service_task_sql
    assert "service_type VARCHAR" in service_task_sql
    assert "schedule_type VARCHAR" in service_task_sql
    assert "config JSONB" in service_task_sql
    assert "description" not in service_task_sql
    assert "client_id" not in service_task_sql
    assert "request_payload" not in service_task_sql
    assert "source_message_id" not in service_task_sql


def test_crawler_tables_follow_latest_job_model():
    crawl_posts_sql = _table_sql("crawl_posts")
    crawl_comments_sql = _table_sql("crawl_comments")

    assert "crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE RESTRICT" in crawl_posts_sql
    assert "first_crawl_job_id" not in crawl_posts_sql
    assert "last_crawl_job_id" not in crawl_posts_sql
    assert "like_count INTEGER" in crawl_posts_sql
    assert "comment_count INTEGER" in crawl_posts_sql
    assert "average_rating NUMERIC(3,2)" not in crawl_posts_sql
    assert "rating_count INTEGER" not in crawl_posts_sql
    assert "service_task_id" not in crawl_posts_sql
    assert "business_id" not in crawl_posts_sql

    assert "crawl_post_id BIGINT" in crawl_comments_sql
    assert "crawl_job_id" not in crawl_comments_sql
    assert "first_crawl_job_id" not in crawl_comments_sql
    assert "last_crawl_job_id" not in crawl_comments_sql
    assert "service_task_id" not in crawl_comments_sql
    assert "business_id" not in crawl_comments_sql

    assert "CREATE TABLE crawl_post_observations" not in SQL
    assert "CREATE TABLE crawl_comment_observations" not in SQL
    assert "CREATE VIEW crawl_posts_with_context" not in SQL
    assert "CREATE VIEW crawl_comments_with_context" not in SQL


def test_metric_and_analysis_tables_remain_available():
    assert "average_rating NUMERIC(3,2)" in _table_sql("post_metric_snapshots")
    assert "rating_count INTEGER" in _table_sql("post_metric_snapshots")
    assert "rating_value NUMERIC(2,1)" in _table_sql("comment_metric_snapshots")
    assert "crawl_job_id" not in _table_sql("post_metric_snapshots")
    assert "crawl_job_id" not in _table_sql("comment_metric_snapshots")
    assert "native_opinion_score NUMERIC(5,2)" in _table_sql("analysis_results")
    assert "CREATE TABLE reputation_score_snapshots" in SQL
    assert "CREATE TABLE alerts" in SQL


def test_reputation_pipeline_migration_tracks_schema_changes():
    migration = (
        ROOT / "database" / "migrations" / "20260712_reputation_pipeline_v1.sql"
    ).read_text(encoding="utf-8")

    assert "ADD COLUMN IF NOT EXISTS rating_value NUMERIC(2,1)" in migration
    assert "ADD COLUMN IF NOT EXISTS average_rating NUMERIC(3,2)" in migration
    assert "CREATE TABLE IF NOT EXISTS reputation_score_snapshots" in migration
    assert "score_explanation JSONB" in migration


def test_latest_relationship_migration_is_safe_and_explicit():
    assert "ADD COLUMN IF NOT EXISTS crawl_job_id BIGINT" in RELATIONSHIP_MIGRATION
    assert "ALTER COLUMN crawl_job_id SET NOT NULL" in RELATIONSHIP_MIGRATION
    assert "ON DELETE RESTRICT" in RELATIONSHIP_MIGRATION
    assert "DROP TABLE public.crawl_post_observations" in RELATIONSHIP_MIGRATION
    assert "DROP TABLE public.crawl_comment_observations" in RELATIONSHIP_MIGRATION
    assert "DROP COLUMN IF EXISTS crawl_job_id" in RELATIONSHIP_MIGRATION
    assert "CREATE OR REPLACE VIEW" not in RELATIONSHIP_MIGRATION
    assert "DELETE FROM" not in RELATIONSHIP_MIGRATION.upper()


def test_legacy_runtime_tables_are_not_recreated():
    created_tables = {
        line.removeprefix("CREATE TABLE ").split(" ", 1)[0]
        for line in SQL.splitlines()
        if line.startswith("CREATE TABLE")
    }

    assert "comments" not in created_tables
    assert "post_metrics" not in created_tables
    assert "comment_metrics" not in created_tables
    assert "search_results" not in created_tables


def test_runtime_debug_directory_is_ignored():
    gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "debug/" in gitignore
