BEGIN;

-- BI-RMP clean rebuild schema.
-- Runtime crawler/service tables are rebuilt from scratch with BIGINT keys.
-- Keep legacy review% tables and master_reviews_enriched outside this reset.

DROP TABLE IF EXISTS client_messages_log CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS reputation_score_snapshots CASCADE;
DROP TABLE IF EXISTS analysis_results CASCADE;
DROP TABLE IF EXISTS comment_metric_snapshots CASCADE;
DROP TABLE IF EXISTS post_metric_snapshots CASCADE;
DROP TABLE IF EXISTS crawl_comment_observations CASCADE;
DROP TABLE IF EXISTS crawl_post_observations CASCADE;
DROP TABLE IF EXISTS crawl_comments CASCADE;
DROP TABLE IF EXISTS crawl_posts CASCADE;
DROP TABLE IF EXISTS crawl_jobs CASCADE;
DROP TABLE IF EXISTS service_tasks CASCADE;
DROP TABLE IF EXISTS business CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

DROP TABLE IF EXISTS comment_metrics CASCADE;
DROP TABLE IF EXISTS post_metrics CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS search_results CASCADE;
DROP TABLE IF EXISTS crawl_logs CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS post_metric CASCADE;
DROP TABLE IF EXISTS crawled_post CASCADE;
DROP TABLE IF EXISTS service_task CASCADE;
DROP TABLE IF EXISTS business_profile CASCADE;
DROP TABLE IF EXISTS client_profile CASCADE;
DROP TABLE IF EXISTS crawled_posts CASCADE;
DROP TABLE IF EXISTS crawledpost CASCADE;
DROP TABLE IF EXISTS facebook_posts CASCADE;
DROP TABLE IF EXISTS facebook_group_posts CASCADE;
DROP TABLE IF EXISTS douyin_posts CASCADE;
DROP TABLE IF EXISTS rednote_posts CASCADE;
DROP TABLE IF EXISTS threads_posts CASCADE;
DROP TABLE IF EXISTS tiktok_posts CASCADE;
DROP TABLE IF EXISTS monitoringtask CASCADE;

DROP VIEW IF EXISTS business_table_editor CASCADE;
DROP VIEW IF EXISTS crawl_jobs_table_editor CASCADE;

CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_user_id VARCHAR UNIQUE,
  name VARCHAR,
  gender VARCHAR,
  birth_date DATE,
  phone VARCHAR,
  email VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_clients_status CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX uq_clients_name_without_line
  ON clients (lower(name))
  WHERE line_user_id IS NULL AND name IS NOT NULL;

CREATE TABLE business (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  name VARCHAR NOT NULL,
  branch_name VARCHAR,
  industry VARCHAR,
  address TEXT,
  config VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_business_status CHECK (status IN ('active', 'inactive'))
);

CREATE UNIQUE INDEX uq_business_name
  ON business(lower(name));

CREATE TABLE service_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  service_type VARCHAR NOT NULL DEFAULT 'reputation_monitoring',
  schedule_type VARCHAR DEFAULT 'once',
  status VARCHAR NOT NULL DEFAULT 'pending',
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_service_tasks_type CHECK (
    service_type IN ('reputation_monitoring', 'reservation_management', 'business_insight')
  ),
  CONSTRAINT chk_service_tasks_schedule CHECK (
    schedule_type IS NULL OR schedule_type IN ('once', 'hourly', 'daily', 'weekly')
  ),
  CONSTRAINT chk_service_tasks_status CHECK (
    status IN ('pending', 'active', 'running', 'paused', 'completed', 'failed', 'cancelled')
  )
);

CREATE TABLE crawl_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
  platform VARCHAR,
  keyword VARCHAR,
  status VARCHAR NOT NULL DEFAULT 'pending',
  trigger_source VARCHAR NOT NULL DEFAULT 'system',
  run_mode VARCHAR NOT NULL DEFAULT 'manual',
  execution_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  total_posts INTEGER NOT NULL DEFAULT 0,
  total_comments INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_crawl_jobs_status CHECK (
    status IN ('pending', 'running', 'success', 'failed', 'cancelled')
  ),
  CONSTRAINT chk_crawl_jobs_run_mode CHECK (run_mode IN ('manual', 'scheduled', 'retry'))
);

CREATE TABLE crawl_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE RESTRICT,
  platform_post_id VARCHAR,
  link TEXT UNIQUE,
  title TEXT,
  author_id VARCHAR,
  author_name VARCHAR,
  content TEXT,
  published_at TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  share_count INTEGER NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  crawl_count INTEGER NOT NULL DEFAULT 1,
  dedupe_key VARCHAR UNIQUE,
  extra_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE crawl_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  platform_comment_id VARCHAR,
  author_id VARCHAR,
  author_name VARCHAR,
  content TEXT NOT NULL,
  published_at TIMESTAMPTZ,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  like_count INTEGER NOT NULL DEFAULT 0,
  reply_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  crawl_count INTEGER NOT NULL DEFAULT 1,
  dedupe_key VARCHAR UNIQUE,
  extra_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE post_metric_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  share_count INTEGER NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  average_rating NUMERIC(3,2),
  rating_count INTEGER,
  extra_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE comment_metric_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_comment_id BIGINT NOT NULL REFERENCES crawl_comments(id) ON DELETE CASCADE,
  like_count INTEGER NOT NULL DEFAULT 0,
  reply_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  rating_value NUMERIC(2,1),
  collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_comment_metric_snapshots_rating_value CHECK (
    rating_value IS NULL OR (rating_value >= 1 AND rating_value <= 5)
  )
);

CREATE TABLE analysis_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type VARCHAR NOT NULL,
  target_id BIGINT NOT NULL,
  sentiment VARCHAR,
  sentiment_score NUMERIC,
  analysis_status VARCHAR,
  analysis_method VARCHAR,
  native_opinion_score NUMERIC(5,2),
  sentiment_score_normalized NUMERIC(5,2),
  engagement_score NUMERIC(5,2),
  impact_weight NUMERIC(4,3),
  confidence_score NUMERIC(4,3),
  provisional_score NUMERIC(5,2),
  unified_score NUMERIC(5,2),
  provisional_rating NUMERIC(3,2),
  unified_rating NUMERIC(3,2),
  scoring_version VARCHAR,
  score_explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
  topic VARCHAR,
  risk_level VARCHAR,
  summary TEXT,
  recommendation TEXT,
  model_name VARCHAR,
  model_version VARCHAR,
  idempotency_key VARCHAR,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ,
  claimed_at TIMESTAMPTZ,
  last_error TEXT,
  worker_id VARCHAR,
  claim_token VARCHAR,
  locked_at TIMESTAMPTZ,
  heartbeat_at TIMESTAMPTZ,
  lease_expires_at TIMESTAMPTZ,
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_analysis_target_type CHECK (target_type IN ('crawl_post', 'crawl_comment')),
  CONSTRAINT chk_analysis_sentiment CHECK (
    sentiment IS NULL OR sentiment IN ('positive', 'negative', 'neutral')
  ),
  CONSTRAINT chk_analysis_risk_level CHECK (
    risk_level IS NULL OR risk_level IN ('low', 'medium', 'high')
  )
);

CREATE TABLE reputation_score_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  platform VARCHAR,
  score_scope VARCHAR NOT NULL DEFAULT 'platform',
  score_status VARCHAR NOT NULL,
  provisional_score NUMERIC(5,2),
  unified_score NUMERIC(5,2),
  provisional_rating NUMERIC(3,2),
  unified_rating NUMERIC(3,2),
  sample_count INTEGER NOT NULL DEFAULT 0,
  effective_sample_count NUMERIC(8,2),
  confidence_score NUMERIC(4,3),
  coverage_ratio NUMERIC(5,4),
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  scoring_version VARCHAR NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_reputation_score_status CHECK (
    score_status IN ('provisional', 'complete', 'insufficient_data', 'native_only', 'native_type_only')
  )
);

CREATE TABLE alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  analysis_result_id BIGINT REFERENCES analysis_results(id) ON DELETE SET NULL,
  alert_type VARCHAR NOT NULL,
  message TEXT NOT NULL,
  status VARCHAR NOT NULL DEFAULT 'pending',
  sent_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_alerts_status CHECK (status IN ('pending', 'sent', 'failed'))
);

CREATE INDEX idx_clients_line_user_id ON clients(line_user_id);
CREATE INDEX idx_business_client_id ON business(client_id);
CREATE INDEX idx_business_config ON business(config);
CREATE INDEX idx_service_tasks_business_id ON service_tasks(business_id);
CREATE INDEX idx_service_tasks_type_status ON service_tasks(service_type, status);
CREATE INDEX idx_crawl_jobs_service_task_id ON crawl_jobs(service_task_id);
CREATE INDEX idx_crawl_jobs_platform_status ON crawl_jobs(platform, status);
CREATE INDEX idx_crawl_jobs_created_at ON crawl_jobs(created_at DESC);
CREATE INDEX idx_crawl_posts_crawl_job_id ON crawl_posts(crawl_job_id);
CREATE INDEX idx_crawl_posts_platform_post_id ON crawl_posts(platform_post_id);
CREATE INDEX idx_crawl_posts_published_at ON crawl_posts(published_at DESC);
CREATE INDEX idx_crawl_posts_last_seen_at ON crawl_posts(last_seen_at DESC);
CREATE INDEX idx_crawl_comments_post_id ON crawl_comments(crawl_post_id);
CREATE INDEX idx_crawl_comments_platform_comment_id ON crawl_comments(platform_comment_id);
CREATE INDEX idx_post_metric_snapshots_post_id ON post_metric_snapshots(crawl_post_id);
CREATE INDEX idx_post_metric_snapshots_collected_at ON post_metric_snapshots(collected_at DESC);
CREATE INDEX idx_comment_metric_snapshots_comment_id ON comment_metric_snapshots(crawl_comment_id);
CREATE INDEX idx_analysis_results_target ON analysis_results(target_type, target_id);
CREATE INDEX idx_analysis_results_status_method ON analysis_results(analysis_status, analysis_method);
CREATE INDEX idx_analysis_results_risk ON analysis_results(risk_level, analyzed_at DESC);
CREATE UNIQUE INDEX idx_analysis_results_idempotency_key
  ON analysis_results(idempotency_key)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_analysis_results_queue
  ON analysis_results(analysis_status, next_attempt_at, created_at)
  WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_analysis_results_lease
  ON analysis_results(lease_expires_at)
  WHERE idempotency_key IS NOT NULL AND analysis_status = 'processing';
CREATE INDEX idx_reputation_score_snapshots_business ON reputation_score_snapshots(business_id, calculated_at DESC);
CREATE INDEX idx_reputation_score_snapshots_platform ON reputation_score_snapshots(platform, score_scope, calculated_at DESC);
CREATE INDEX idx_alerts_business_id ON alerts(business_id);
CREATE INDEX idx_alerts_status ON alerts(status);

COMMENT ON TABLE clients IS 'Line Bot service customer or business owner identity.';
COMMENT ON TABLE business IS 'Store, merchant, brand, or branch monitored by BI-RMP.';
COMMENT ON TABLE service_tasks IS 'Business-level service task. Runtime options live in config.';
COMMENT ON TABLE crawl_jobs IS 'One crawler execution for one platform or crawler strategy.';
COMMENT ON TABLE crawl_posts IS 'Canonical crawled post/review/article table with latest content and interaction state.';
COMMENT ON TABLE crawl_comments IS 'Canonical crawled comment/reply/review table with latest content and interaction state.';
COMMENT ON TABLE post_metric_snapshots IS 'Historical post interaction snapshots ordered by collected_at.';
COMMENT ON TABLE comment_metric_snapshots IS 'Historical comment interaction snapshots ordered by collected_at.';
COMMENT ON TABLE analysis_results IS 'AI/ML analysis outputs for posts or comments.';
COMMENT ON TABLE reputation_score_snapshots IS 'Historical provisional and complete reputation scores by business and platform.';
COMMENT ON TABLE alerts IS 'Notification records derived from high-risk analysis results.';

CREATE TABLE client_messages_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  line_user_id VARCHAR NOT NULL,
  message_text TEXT,
  direction VARCHAR NOT NULL DEFAULT 'incoming',
  intent VARCHAR,
  session_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_message_direction CHECK (direction IN ('incoming', 'outgoing'))
);

CREATE INDEX idx_client_messages_line_user ON client_messages_log(line_user_id);

COMMENT ON TABLE client_messages_log IS 'History of LINE user messages and intent session states.';

CREATE TABLE crawl_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_task_id BIGINT REFERENCES service_tasks(id) ON DELETE CASCADE,
  level VARCHAR(10) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_crawl_logs_task_id ON crawl_logs(service_task_id);

COMMENT ON TABLE crawl_logs IS 'Execution logs generated during crawler runs.';

COMMENT ON COLUMN crawl_posts.crawl_job_id IS 'Crawl job that produced the current latest post state.';

COMMIT;
