-- Create crawl_logs table to store crawler execution logs
CREATE TABLE IF NOT EXISTS crawl_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_task_id BIGINT REFERENCES service_tasks(id) ON DELETE CASCADE,
  level VARCHAR(10) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crawl_logs_task_id ON crawl_logs(service_task_id);

COMMENT ON TABLE crawl_logs IS 'Execution logs generated during crawler runs.';
