BEGIN;

ALTER TABLE post_metric_snapshots
  ADD COLUMN IF NOT EXISTS average_rating NUMERIC(3,2),
  ADD COLUMN IF NOT EXISTS rating_count INTEGER,
  ADD COLUMN IF NOT EXISTS extra_data JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE comment_metric_snapshots
  ADD COLUMN IF NOT EXISTS rating_value NUMERIC(2,1);

UPDATE comment_metric_snapshots cms
SET rating_value = NULLIF(cc.extra_data->>'rating_value', '')::numeric
FROM crawl_comments cc
WHERE cms.crawl_comment_id = cc.id
  AND cms.rating_value IS NULL
  AND cc.extra_data ? 'rating_value'
  AND NULLIF(cc.extra_data->>'rating_value', '') IS NOT NULL
  AND NULLIF(cc.extra_data->>'rating_value', '') ~ '^[0-9]+(\.[0-9]+)?$'
  AND NULLIF(cc.extra_data->>'rating_value', '')::numeric BETWEEN 1 AND 5;

ALTER TABLE comment_metric_snapshots
  DROP CONSTRAINT IF EXISTS chk_comment_metric_snapshots_rating_value;

ALTER TABLE comment_metric_snapshots
  ADD CONSTRAINT chk_comment_metric_snapshots_rating_value
  CHECK (rating_value IS NULL OR (rating_value >= 1 AND rating_value <= 5));

ALTER TABLE analysis_results
  ADD COLUMN IF NOT EXISTS analysis_status VARCHAR,
  ADD COLUMN IF NOT EXISTS analysis_method VARCHAR,
  ADD COLUMN IF NOT EXISTS native_opinion_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS sentiment_score_normalized NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS engagement_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS impact_weight NUMERIC(4,3),
  ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(4,3),
  ADD COLUMN IF NOT EXISTS provisional_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS unified_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS provisional_rating NUMERIC(3,2),
  ADD COLUMN IF NOT EXISTS unified_rating NUMERIC(3,2),
  ADD COLUMN IF NOT EXISTS scoring_version VARCHAR,
  ADD COLUMN IF NOT EXISTS score_explanation JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS reputation_score_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  platform VARCHAR,
  score_scope VARCHAR NOT NULL DEFAULT 'platform',
  score_status VARCHAR NOT NULL,
  provisional_score NUMERIC(5,2),
  unified_score NUMERIC(5,2),
  provisional_rating NUMERIC(3,2),
  unified_rating NUMERIC(3,2),
  sample_count INTEGER NOT NULL DEFAULT 0,
  effective_sample_count NUMERIC(8,2),
  confidence_score NUMERIC(4,3),
  coverage_ratio NUMERIC(5,4),
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  scoring_version VARCHAR NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE reputation_score_snapshots
  DROP CONSTRAINT IF EXISTS chk_reputation_score_status;

ALTER TABLE reputation_score_snapshots
  ADD CONSTRAINT chk_reputation_score_status
  CHECK (score_status IN (
    'provisional',
    'complete',
    'insufficient_data',
    'native_only',
    'native_type_only'
  ));

CREATE INDEX IF NOT EXISTS idx_analysis_results_status_method
  ON analysis_results(analysis_status, analysis_method);

CREATE INDEX IF NOT EXISTS idx_reputation_score_snapshots_business
  ON reputation_score_snapshots(business_id, calculated_at DESC);

CREATE INDEX IF NOT EXISTS idx_reputation_score_snapshots_platform
  ON reputation_score_snapshots(platform, score_scope, calculated_at DESC);

COMMIT;
