-- Apply missing observation and metric snapshot tables to existing Supabase databases.
-- Idempotent: preserves existing canonical rows and existing snapshot/observation data.

BEGIN;

CREATE TABLE IF NOT EXISTS crawl_post_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
  crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE CASCADE,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  platform VARCHAR,
  keyword VARCHAR,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  source_rank INTEGER,
  raw_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (crawl_job_id, crawl_post_id)
);

CREATE TABLE IF NOT EXISTS crawl_comment_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
  crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE CASCADE,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  crawl_comment_id BIGINT NOT NULL REFERENCES crawl_comments(id) ON DELETE CASCADE,
  platform VARCHAR,
  keyword VARCHAR,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  source_rank INTEGER,
  raw_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (crawl_job_id, crawl_comment_id)
);

CREATE TABLE IF NOT EXISTS post_metric_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  crawl_job_id BIGINT REFERENCES crawl_jobs(id) ON DELETE SET NULL,
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  share_count INTEGER NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comment_metric_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crawl_comment_id BIGINT NOT NULL REFERENCES crawl_comments(id) ON DELETE CASCADE,
  crawl_job_id BIGINT REFERENCES crawl_jobs(id) ON DELETE SET NULL,
  like_count INTEGER NOT NULL DEFAULT 0,
  reply_count INTEGER NOT NULL DEFAULT 0,
  reaction_count INTEGER NOT NULL DEFAULT 0,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_post_metric_snapshots_post_job
  ON post_metric_snapshots(crawl_post_id, crawl_job_id)
  WHERE crawl_job_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_comment_metric_snapshots_comment_job
  ON comment_metric_snapshots(crawl_comment_id, crawl_job_id)
  WHERE crawl_job_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_business ON crawl_post_observations(business_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_service_task ON crawl_post_observations(service_task_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_job ON crawl_post_observations(crawl_job_id);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_post ON crawl_post_observations(crawl_post_id);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_platform_keyword ON crawl_post_observations(platform, keyword);

CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_business ON crawl_comment_observations(business_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_service_task ON crawl_comment_observations(service_task_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_job ON crawl_comment_observations(crawl_job_id);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_post ON crawl_comment_observations(crawl_post_id);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_comment ON crawl_comment_observations(crawl_comment_id);

CREATE INDEX IF NOT EXISTS idx_post_metric_snapshots_post_id ON post_metric_snapshots(crawl_post_id);
CREATE INDEX IF NOT EXISTS idx_post_metric_snapshots_job_id ON post_metric_snapshots(crawl_job_id);
CREATE INDEX IF NOT EXISTS idx_post_metric_snapshots_collected_at ON post_metric_snapshots(collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_comment_metric_snapshots_comment_id ON comment_metric_snapshots(crawl_comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_metric_snapshots_job_id ON comment_metric_snapshots(crawl_job_id);

COMMENT ON TABLE crawl_post_observations IS 'Full history of which crawl job observed which canonical post for a business/service task.';
COMMENT ON TABLE crawl_comment_observations IS 'Full history of which crawl job observed which canonical comment for a business/service task.';
COMMENT ON TABLE post_metric_snapshots IS 'Historical post interaction snapshots captured per crawl job.';
COMMENT ON TABLE comment_metric_snapshots IS 'Historical comment interaction snapshots captured per crawl job.';

COMMIT;
