-- Replace first/last crawl job endpoint pointers with full job observation history.
-- This migration is intended for the existing Supabase database.

BEGIN;

DROP INDEX IF EXISTS idx_crawl_posts_first_job;
DROP INDEX IF EXISTS idx_crawl_posts_last_job;
DROP INDEX IF EXISTS idx_crawl_comments_first_job;
DROP INDEX IF EXISTS idx_crawl_comments_last_job;

ALTER TABLE crawl_posts
  DROP COLUMN IF EXISTS first_crawl_job_id,
  DROP COLUMN IF EXISTS last_crawl_job_id;

ALTER TABLE crawl_comments
  DROP COLUMN IF EXISTS first_crawl_job_id,
  DROP COLUMN IF EXISTS last_crawl_job_id;

CREATE TABLE IF NOT EXISTS crawl_post_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
  crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE CASCADE,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  platform VARCHAR,
  keyword VARCHAR,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  source_rank INTEGER,
  raw_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (crawl_job_id, crawl_post_id)
);

CREATE TABLE IF NOT EXISTS crawl_comment_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  service_task_id BIGINT NOT NULL REFERENCES service_tasks(id) ON DELETE CASCADE,
  crawl_job_id BIGINT NOT NULL REFERENCES crawl_jobs(id) ON DELETE CASCADE,
  crawl_post_id BIGINT NOT NULL REFERENCES crawl_posts(id) ON DELETE CASCADE,
  crawl_comment_id BIGINT NOT NULL REFERENCES crawl_comments(id) ON DELETE CASCADE,
  platform VARCHAR,
  keyword VARCHAR,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  source_rank INTEGER,
  raw_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (crawl_job_id, crawl_comment_id)
);

CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_business ON crawl_post_observations(business_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_service_task ON crawl_post_observations(service_task_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_job ON crawl_post_observations(crawl_job_id);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_post ON crawl_post_observations(crawl_post_id);
CREATE INDEX IF NOT EXISTS idx_crawl_post_observations_platform_keyword ON crawl_post_observations(platform, keyword);

CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_business ON crawl_comment_observations(business_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_service_task ON crawl_comment_observations(service_task_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_job ON crawl_comment_observations(crawl_job_id);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_post ON crawl_comment_observations(crawl_post_id);
CREATE INDEX IF NOT EXISTS idx_crawl_comment_observations_comment ON crawl_comment_observations(crawl_comment_id);

COMMENT ON TABLE crawl_post_observations IS 'Full history of which crawl job observed which canonical post for a business/service task.';
COMMENT ON TABLE crawl_comment_observations IS 'Full history of which crawl job observed which canonical comment for a business/service task.';

COMMIT;
