-- Migration: Create client_messages_log table to save LINE user messaging history and session state
CREATE TABLE client_messages_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  line_user_id VARCHAR NOT NULL,
  message_text TEXT,
  direction VARCHAR NOT NULL DEFAULT 'incoming',
  intent VARCHAR,
  session_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_message_direction CHECK (direction IN ('incoming', 'outgoing'))
);

CREATE INDEX idx_client_messages_line_user ON client_messages_log(line_user_id);
