from __future__ import annotations

DEFAULT_PTT_FALLBACK_BOARDS = (
    "Food",
    "Tainan",
    "TaichungBun",
    "Hsinchu",
    "Kaohsiung",
    "Taipei",
    "Lifeismoney",
    "Gossiping",
)

PTT_QUERY_MATCH_MIN_RATIO = 0.7

PTT_FETCH_ATTEMPTS = 3
PTT_RETRY_BASE_DELAY_SECONDS = 1.0
PTT_RETRY_MAX_DELAY_SECONDS = 8.0
PTT_RETRY_JITTER_MIN_SECONDS = 0.2
PTT_RETRY_JITTER_MAX_SECONDS = 1.2

PTT_ARTICLE_DELAY_MIN_SECONDS = 0.8
PTT_ARTICLE_DELAY_MAX_SECONDS = 2.2
PTT_BOARD_DELAY_MIN_SECONDS = 1.0
PTT_BOARD_DELAY_MAX_SECONDS = 3.0

RETRYABLE_HTTP_STATUS = {408, 425, 429, 500, 502, 503, 504}
NON_RETRYABLE_HTTP_STATUS = {400, 401, 403, 404, 410}

# Phase 2 configurations
PTT_INDEX_SCAN_MAX_PAGES = 3
PTT_INDEX_SCAN_MAX_RESULTS_PER_BOARD = 10
PTT_QUERY_VARIANT_LIMIT = 5
PTT_MIN_RELEVANCE_SCORE = 2.0
PTT_CACHE_TTL_SECONDS = 24 * 60 * 60
PTT_TERMINAL_QUARANTINE_TTL_SECONDS = 7 * 24 * 60 * 60
PTT_TRANSIENT_QUARANTINE_TTL_SECONDS = 60 * 60
PTT_CACHE_TTL_HOURS = 24
